version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        patterns:
          - "*eslint*"
          - "*prettier*"
          - "*typescript*"
          - "*vite*"
          - "*vitest*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"