name: バグ報告
description: バグや不具合を報告する
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## バグ報告
        発見したバグや不具合について報告してください。

  - type: textarea
    id: description
    attributes:
      label: バグの説明
      description: どのような問題が発生しているか詳しく説明してください
      placeholder: 期待される動作と実際の動作の違いを明確に記載してください
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 再現手順
      description: バグを再現するための手順を記載してください
      placeholder: |
        1. '...'へ移動
        2. '...'をクリック
        3. '...'まで下にスクロール
        4. エラーが表示される
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 期待される動作
      description: 本来どのように動作すべきか説明してください
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: 実際の動作
      description: 実際にどのような動作になったか説明してください
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 深刻度
      options:
        - 致命的（サービスが利用できない）
        - 重大（主要機能が動作しない）
        - 中程度（一部機能に影響）
        - 軽微（UXに影響）
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: 環境
      description: ブラウザ、OS、バージョンなど
      placeholder: "Chrome 120, Windows 11"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: エラーログ
      description: コンソールエラーやログがあれば貼り付けてください
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: スクリーンショット
      description: 問題を示すスクリーンショットがあれば添付してください

  - type: checkboxes
    id: checklist
    attributes:
      label: 確認事項
      options:
        - label: 最新バージョンで問題が発生している
          required: true
        - label: 既存のIssueを検索した
          required: true
        - label: 再現可能である
          required: false